### PR TITLE
Fixes problem next_page

### PR DESCRIPTION
**Pull request by bdc34**
Fixes screening of the /login next_page query parameter to avoid having a logged in user sent off site.

The regex is intended to limit to the next_page to either relative or subdomains of arxiv.org. But the relative part was unanchored. 

Related to #89 and https://arxiv-org.atlassian.net/browse/ARXIVCE-333

### CODE REVIEW

**Review by jonathanhyoung — APPROVED** [review]

**Comment by edent** [comment]
I don't think this fixes the problem entirely.

For example `https://arxiv.org/login?next_page=//example.com` redirects. That's because the redirect uses a protocol relative URl.

This also doesn't check for users who are already logged in.  For example, if a user is *already* logged in then visiting `https://arxiv.org/login?next_page=https://example.com` will still redirect them to an external site.

**Comment by bdc34** [comment]
Thanks, I've fixed the already logged in issue. Working on the other one.

**Comment by bdc34** [comment]
Thanks, I've deployed a change that should fix both the protocol relative URI bug and the already logged in bug.

Thanks, let me know what you think.

--
Brian Caruso
Senior Developer at arXiv

arXiv.org Cornell Tech
***@***.*** ***@***.***>
[cid:93eaae26-5409-4cbb-ada1-8248df9bb886]
________________________________

**Comment by edent** [comment]
LGTM.

**Comment by enbrown** [comment]
FYI, putting some encoded characters in the next_page query parameter will cause different server errors:

* https://arxiv.org/login?next_page=/test will go to the nonexistant /test page as expected
* https://arxiv.org/login?next_page=/test%1f will cause an Internal Server Error
* https://arxiv.org/login?next_page=/test%0D will cause a different Internal Server Error (different page so probably triggering at a different point in the code)

Finally, the [regex](https://github.com/arXiv/arxiv-auth/blob/734f88e5839acebe34252cbb3eb8ce71a31aa117/accounts/accounts/config.py#L51) doesn't check for subdomains correctly. Thus `https://arxiv.org/login?next_page=https://evil-arxiv.org/` will pass the regex and yet send the user to evil-arxiv.org.

**Pull request merged**
