### PR TITLE
ARXIVNG-1468 Endorsements should be represented more efficiently

### PR DESCRIPTION
**Pull request by erickpeirson**
Right now, endorsements are a long list of categories on the session object. This is pretty big and unwieldy.

This PR adds compression for endorsed categories using wildcards. If a user/client is authorized for all categories in a particular archive, the category names will be compressed to a wildcard ``archive.*`` representation. If the user/client is authorized for all categories in the system, this will be compressed to "*.*".

# Checking endorsements
Endorsements for submission are represented as categories on the ``Authorization`` object (generally ``session.authorizations.endorsements``). To avoid enumerating all of the categories and archives in the system, we compress endorsed categories wherever possible using wildcard notation. For example, ``cs.*`` represents an endorsement for all subjects in the ``cs`` archive. ``*.*`` represents an endorsement for all categories in the system.

For convenience, endorsement authorizations can be checked with the ``Authorizations.endorsed_for`` method. For example:

```python
from flask import request

if request.session.authorizations.endorsed_for("cs.AI"):
    print("This user/client is endorsed for cs.AI")
```

### CODE REVIEW

**Comment by JaimieMurdock** [comment]
Why use "." for the master key instead of "*"?

**Comment by erickpeirson** [comment]
@JaimieMurdock Where do you see that?

**Comment by JaimieMurdock** [comment]
The `.`/`*` was from the PR description at the top :point_up:, realizing now it's a github markdown issue - `'*.*'` rendered a bold period '*.*'.

**Comment by erickpeirson** [comment]
Nah this is just the backend stuff; UI is next

**Pull request merged**
